### ISSUE TITLE
catalogul de note nu este persistent

### ISSUE THREAD

**Issue by alin-miu-scoalainformala** [alin-miu-scoalainformala/siit-grupa3#58]
@iulius83 elevii adaugati in catalogul si nici notele lor nu se salveaza in firebase

**Comment by iulius83** [comment]
nu am avut tema sa facem catalogul cu firebase :P

**Comment by alin-miu-scoalainformala** [comment]
Asa e, ai dreptate. Nu e bug, e feature :))

O sa dau ca tema sa faceti si catalogul cu firebase :)

**Comment by iulius83** [comment]
Roger, will do! :)

**Comment by iulius83** [comment]
this bug is fixed... new bugs introduced :P
